### ISSUE TITLE
Consider using `re` instead of `BeautifulSoup`

### ISSUE THREAD

**Issue by ronnie-llamado** [mbillow/python-redpocket#1]
What a coincidence on the timing on the project! It is surely an improvement over [pyredpocket](https://github.com/ronnie-llamado/pyRedPocket).

It might be worth considering utilizing `re` to search for the `csrf`; utilizing a standard package instead of requiring `BeautifulSoup`. It's a simple search, so `BeatutifulSoup` seems a bit overkill.

```python
html = requests.get('https://www.redpocket.com/login')
re.search(r'<input type="hidden" name="csrf" value="([\w|-]+)">', html.text).group(1)
```

**Comment by mbillow** [comment]
I definitely searched Google before writing this. It must have been right before Google index PyPI for your module. 

I was thinking the same thing as I was adding BS. I’ll take a look at the diff tomorrow when I’m not on my phone. 

Purely out of curiosity, what lead you to make your module in the first place? I made a Home Assistant component to easily view my plan info in a easy to get to place.

**Comment by ronnie-llamado** [comment]
Hey no worries, I'll probably archive my project in favor of this one as it's built up more.

That's actually pretty cool. I was just interested in understanding my data usage better. For the past year, I've been using a cronjob to pull data every half hour. Sadly, the data is rather boring.
